{
 "title": "Spring Boot Http Observability Example",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/api/v1/hello\"} / http_server_requests_seconds_count{ uri=\"/api/v1/hello\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Top request count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/api/v1/hello\"}",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Top request time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds_sum{uri=\"/api/v1/hello\"}) by (method, status)\n/\navg(http_server_requests_seconds_count{uri=\"/api/v1/hello\"}) by (method, status)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/api/v1/hello\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}